### ISSUE TITLE
API List

### ISSUE THREAD

**Issue by ChmlGr** [eventoL/eventoL-api#1]
- [x]  GET /categories
- [x]  GET /tags/q= (Para Autocomplete)
- [x]  GET /events/lat/long/page  (1)
- [x]  GET /events/lat/long/page/q= (Para searchbox) (2)
- [x]  GET /events/idEvent
- [x]  GET /users/idUser

(1) lat y long para ordenarlo y pagination
(2) query tiene que aplicar a tags, categories y event. Devolverlo en 3 arrays separados

**Comment by FedeG** [comment]
La búsqueda de eventos queda así:
- [x] /events/long/lat/
- [x] /events/long/lat/?page=1
- [x] /events/long/lat/?distance=10
- [x] /events/long/lat/?limit=10
- [x] /events/long/lat/?page=1&limit=10&distance=10

**Comment by FedeG** [comment]
También las query string son las siguientes: https://github.com/wprl/baucis/wiki/Query-String-Parameters
